wandb_version: 1

save_path:
  desc: null
  value: ../../satellite_model
version:
  desc: null
  value: v9
cuda:
  desc: null
  value: '0'
num_workers:
  desc: null
  value: 4
wandb:
  desc: null
  value: 'yes'
pretrain:
  desc: null
  value: 'no'
pretrained_model:
  desc: null
  value: practice
error_signal:
  desc: null
  value: 'no'
ts_batch_size:
  desc: null
  value: 88
vs_batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.0005
epochs:
  desc: null
  value: 200
optimizer:
  desc: null
  value: AdamW
scheduler:
  desc: null
  value: lambda
loss:
  desc: null
  value: bce
valid_epoch:
  desc: null
  value: 8
model:
  desc: null
  value: unet
training_date:
  desc: null
  value: '240322'
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711043617.0
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
